platform: x64
image: Visual Studio 2019
environment:
  matrix:
    - ARCH: x86_64
      VC_ARCH: x64
cache:
  - '%LOCALAPPDATA%\dub -> dub.selections.json'
install:
  - ps: $latest = (Invoke-WebRequest "https://ldc-developers.github.io/LATEST").toString().trim()
  - ps: $url = "https://github.com/ldc-developers/ldc/releases/download/v$($latest)/ldc2-$($latest)-windows-$($env:VC_ARCH).7z";
  - ps: Push-Location "$($env:TMP)"
  - ps: Invoke-WebRequest $url -OutFile ".\ldc.7z"
  - ps: 7z x ldc.7z > $null
  - ps: Pop-Location
  - ps: $env:PATH += ";$($env:TMP)\ldc2-$($latest)-windows-$($env:VC_ARCH)\bin"
  - call msvcEnv %VC_ARCH%
build_script:
  - if defined APPVEYOR_REPO_TAG_NAME (set BUILD=release) else (set BUILD=debug)
  - dub build --arch=%ARCH% --compiler=ldc2 --build=%BUILD%
after_build:
  - if defined APPVEYOR_REPO_TAG_NAME (set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%) else (set TAG_NAME=untagged)
  - 7z -mx=9 a dls-%TAG_NAME%.windows.%ARCH%.zip dls.exe LICENSE.txt
test_script:
  - dub test --arch=%ARCH% --compiler=ldc2 --main-file=tests\main.d
artifacts:
  - path: dls-*.zip
deploy:
  - provider: GitHub
    auth_token: $(GITHUB_API_KEY)
    artifact: /dls-.*\.zip/
    on:
      appveyor_repo_tag: true
