sudo: required
dist: xenial
language: d
matrix:
  fast_finish: true
  include:
    - d: ldc
      os: linux
      env: ARCH=x86_64
    - d: ldc
      os: osx
      env: ARCH=x86_64
    - d: dmd-beta
      os: linux
    - d: ldc-beta
      os: linux
  allow_failures:
    - d: dmd-beta
    - d: ldc-beta
cache:
  directories:
    - $HOME/.dub
before_script:
  - ln -s /usr/bin/ld.gold ~/ld
script:
  - if [[ -n $TRAVIS_TAG ]]; then export BUILD=release; export OP=build; fi
  - export PATH="$HOME:$PATH"
  - dub ${OP:-test --main-file=tests/main.d} --arch=${ARCH:-x86_64} --compiler=$DC --build=${BUILD:-debug}
before_deploy:
  - if which strip; then strip dls; fi
  - zip -9 dls-${TRAVIS_TAG:-untagged}.$TRAVIS_OS_NAME.$ARCH.zip dls LICENSE.txt
  - export TARGET_COMMITISH="$(echo -n release/$TRAVIS_TAG | sed 's/.[0-9]*$/.x/')"
deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  target_commitish: "$TARGET_COMMITISH"
  file_glob: true
  file: dls-*.zip
  skip_cleanup: true
  on:
    condition: "-n $ARCH"
    repo: d-language-server/dls
    tags: true
