<div class="elavenn_sidebar"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="wo_about_wrapper_parent">
	<div class="wo_about_wrapper">
		<div class="hero hero-overlay">
			<div class="container">
				<h1 class="text-center">
					<?php echo $wo['lang']['about'];?> <?php echo $wo['config']['siteName'];?> <br>
					<small class="site_desc text-center"><?php echo $wo['description'];?></small>
				</h1>
			</div>
		</div>
		<div class="full-width-picture" style="background-image: url(<?php echo $wo['config']['theme_url'];?>/img/about-us.jpg);"></div>
	</div>
</div>

<div class="page-margin wo_about_page_margin">
   <div class="wow_content">
      <div class="setting-well">
        <?php echo $wo['terms']['about'];?>
      </div>
   </div>
</div>

<!--
<script src="https://unpkg.com/riot@6/riot+compiler.min.js"></script>

<todo></todo>



<script src="./todo.riot" type="riot"></script>
<script>
 riot.compile().then(() => {
	 riot.mount('todo', {
		 title: 'I want to behave!',
		 items: [
			 { title: 'seen', done: true },
			 { title: 'configuration and security',  hidden: true },
			 { title: 'Be less provocative'  },
			 { title: 'Be nice to people' }
		 ]
	 })
 })
</script>
-->


<?php

//https://www.example-code.com/


/*
<%
Response.ContentType = "text/event-stream"
Response.Expires = -1
Response.Write("data: The server time is: " & now())
Response.Flush()
%>
<li>
	 <a href="<?php echo Wo_SeoLink('index.php?link1=welcome&last_url=' . $wo['actual_link']);?>">
	 <?php echo $wo['lang']['login']; ?>
	 </a>
</li>
http://localhost:8081/examples/logo1.jpg
<search></search>
*/

echo '<img  src="http://localhost:8081/examples/logo1.jpg" class="responsive" heigt="60" width="60"/>';
echo '<img  src="http://localhost:8081/examples/logo1dark.jpg" class="responsive" heigt="60" width="60"/>';


?>
<?php echo '<img  src="http://localhost:8081/examples/tunisia.jpg" class="responsive" heigt="60" width="60"/>';?>




<?php
	 ini_set (user_agent, "IE");
	 ini_set (default_socket_timeout, "3");
	 error_reporting(0);
	 $theurl="http://localhost/login.asp";
	 $filestring=file_get_contents("$theurl") ;
	 echo "$filestring";
	 ?>


	 <?php
	 	ini_set (user_agent, "IE");
	 	ini_set (default_socket_timeout, "3");
	 	error_reporting(0);
	 	$theurl="http://localhost/navs2.asp";
	 	$filestring=file_get_contents("$theurl") ;
	 	echo "$filestring";
	 	?>

		<?php
 	 	 ini_set (user_agent, "IE");
 	 	 ini_set (default_socket_timeout, "3");
 	 	 error_reporting(0);
 	 	 //$theurl="http://localhost/mydesign.asp";
 	 	 //$filestring=file_get_contents("$theurl") ;
 	 	 //echo "$filestring";
 	 	 ?>








	 <?php
	 	 ini_set (user_agent, "IE");
	 	 ini_set (default_socket_timeout, "3");
	 	 error_reporting(0);
	 	 $theurl="http://localhost/mydesign.asp";
	 	 $filestring=file_get_contents("$theurl") ;
	 	 echo "$filestring";
	 	 ?>
