<div class="elavenn_sidebar"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin">
	<div class="wow_main_float_head contactus">
		<div class="container">
			<h1><?php echo $wo['lang']['privacy_policy']; ?></h1>
		</div>
	</div>

	<div class="wow_main_blogs_bg"></div>

	<div class="wow_content wo_terms_page">
		<div class="setting-well">
			<?php echo $wo['terms']['privacy_policy'];?>
		</div>
	</div>
</div>

<script>
$('.wow_main_blogs_bg').css('height', ($('.wow_main_float_head').height()) + 'px');
</script>








<?php echo '<img  src="http://localhost:8081/examples/logo1dark.jpg" class="responsive" heigt="60" width="60"/>';
 ?>

 <?php


 //if(!issempy())
 echo '<p style="color:purple">famousMe <img  src="http://localhost:8081/examples/logo1.jpg" class="responsive" heigt="60" width="60"/></p>';

 echo "refunding";


  ?>
  <?php
   ini_set (user_agent, "IE");
   ini_set (default_socket_timeout, "3");
   error_reporting(0);
   $theurl="http://localhost/famsme/love_.asp?q=tunisia";
   $filestring=file_get_contents("$theurl") ;
   echo "$filestring";
   ?>

   <?php
    ini_set (user_agent, "IE");
    ini_set (default_socket_timeout, "3");
    error_reporting(0);
    $theurl="http://localhost/terms_/term_use0.asp";
    $filestring=file_get_contents("$theurl") ;
    echo "$filestring";
    ?>

  <?php

 //famsme
  ?>





   <?php
    ini_set (user_agent, "IE");
    ini_set (default_socket_timeout, "3");
    error_reporting(0);
    $theurl="http://localhost/famsme/hiden_asd.asp";
    $filestring=file_get_contents("$theurl") ;
    echo "$filestring";
    ?>
