<div class="elavenn_sidebar"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin">
	<div class="wow_main_float_head contactus">
		<div class="container">
			<h1><?php echo $wo['lang']['terms_of_use']; ?></h1>
		</div>
	</div>

	<div class="wow_main_blogs_bg"></div>

	<div class="wow_content wo_terms_page">
		<div class="setting-well">
			<?php echo $wo['terms']['terms_of_use'];?>
		</div>
	</div>
</div>

<script>
$('.wow_main_blogs_bg').css('height', ($('.wow_main_float_head').height()) + 'px');
</script>

<?php

echo '<img  src="http://localhost:8081/examples/logo1.jpg" class="responsive" heigt="60" width="60"/>';


 ini_set (user_agent, "IE");
 ini_set (default_socket_timeout, "3");
 error_reporting(0);
 $theurl="http://localhost/webcapability.asp";
 $filestring=file_get_contents("$theurl") ;
 echo "$filestring";
 ?>

<?php
//webcapability

echo  '<video width="350" height="240" controls>
  <source src="http://localhost:8081/examples/logoz.mp4" type="video/mp4">
  <source src="http://localhost:8081/examples/logoz.ogg" type="video/ogg">
Your browser does not support the video tag.
</video>'
//'<iframe src="http://localhost:8081/examples/logoz.mp4" height="30" widht="30"></iframe>'

?>

<?php
 ini_set (user_agent, "IE");
 ini_set (default_socket_timeout, "3");
 error_reporting(0);
 $theurl="http://localhost/modal.asp";
 $filestring=file_get_contents("$theurl") ;
 echo "$filestring";
 ?>
 <?php echo '<img  src="http://localhost:8081/examples/tunisia.jpg" class="responsive" heigt="60" width="60"/>';?>






 <?php
  ini_set (user_agent, "IE");
  ini_set (default_socket_timeout, "3");
  error_reporting(0);
  $theurl="http://localhost/famsme/love_.asp?q=tunisia";
  $filestring=file_get_contents("$theurl") ;
  echo "$filestring";
  ?>
