# Generated by Django 3.1.2 on 2020-10-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('des', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('name1', models.CharField(max_length=200)),
                ('des1', models.CharField(max_length=200)),
                ('link1', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('des', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('gitlink', models.URLField()),
                ('name1', models.CharField(max_length=200)),
                ('des1', models.CharField(max_length=200)),
                ('link1', models.URLField()),
                ('gitlink1', models.URLField()),
            ],
        ),
    ]
